### ISSUE TITLE
There is no error data in findUser catch

### ISSUE THREAD

**Issue by gitofchang** [jgretz/node-bits-jwt#10]
I'd like to add error data in findUser catch clause.
https://github.com/jgretz/node-bits-jwt/blob/master/src/strategies/user_auth/authorize.js#L95

I've also made the pull request.
https://github.com/jgretz/node-bits-jwt/pull/9

**Comment by jgretz** [comment]
See the comment made on the PR - feel free to reopen if you decide to make an updated pr
